In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

Mounted at /content/drive

In [48]:
order_items_path='/content/drive/MyDrive/Jet2premium/order_items.csv'
orders_path='/content/drive/MyDrive/Jet2premium/orders.csv'
geo_path='/content/drive/MyDrive/Jet2premium/geography.csv'
promo_path='/content/drive/MyDrive/Jet2premium/promotions.csv'
web_path = '/content/drive/MyDrive/Jet2premium/web_traffic.csv'
product_path = '/content/drive/MyDrive/Jet2premium/products.csv'
df_product = pd.read_csv(product_path)
df_web = pd.read_csv(web_path)
df_promo=pd.read_csv(promo_path)
df_items=pd.read_csv(order_items_path)
df_or=pd.read_csv(orders_path)
df_geo=pd.read_csv(geo_path)

**Q2. Phân khúc sản phẩm (segment) nào trong products.csv có tỷ suất lợi nhuận gộp trung bình cao nhất, với công thức (price − cogs)/price?**
A) Premium
B) Performance
C) Activewear
D) Standard

In [49]:
df_product.head()

,product_id,product_name,category,segment,size,color,price,cogs
0,536,SaigonFlex UC-01,Streetwear,Everyday,S,green,11059.650000,9704.842875
1,537,SaigonFlex UC-02,Streetwear,Everyday,M,silver,9523.076013,5393.870254
2,538,SaigonFlex UC-03,Streetwear,Everyday,L,pink,15951.633158,11371.919278
3,539,SaigonFlex UC-04,Streetwear,Everyday,XL,yellow,15753.717299,8573.172954
4,540,SaigonFlex UC-05,Streetwear,Everyday,S,red,15766.334536,14063.570406

In [50]:
df_product.info()
print(df_product.isnull().sum())
print(df_product.duplicated().sum())
print(df_product.nunique().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2412 entries, 0 to 2411
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2412 non-null   int64
 1   product_name  2412 non-null   object
 2   category      2412 non-null   object
 3   segment       2412 non-null   object
 4   size          2412 non-null   object
 5   color         2412 non-null   object
 6   price         2412 non-null   float64
 7   cogs          2412 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 150.9+ KB
product_id      0
product_name    0
category        0
segment         0
size            0
color           0
price           0
cogs            0
dtype: int64
0
8981

In [54]:
#công thức đề cho(price - cogs) / price
df_product['gross_margin'] = (df_product['price'] - df_product['cogs']) / df_product['price']
#Tỷ suất lợi nhuận gộp trung bình
segment= df_product.groupby('segment')['gross_margin'].mean().sort_values(ascending=False)
print('Tỷ suất lợi nhuận gộp trung bình theo từng segment',segment)
#Tìm ra cao nhất
max_segment=segment.index[0]
max_value=segment.iloc[0]
print(f'Phân khúc {max_segment} có tỷ suất lợi nhuận cao nhất với {max_value}')

Tỷ suất lợi nhuận gộp trung bình theo từng segment segment
Standard       0.313442
Premium        0.285377
All-weather    0.284176
Activewear     0.265600
Performance    0.263650
Balanced       0.258038
Trendy         0.240758
Everyday       0.236343
Name: gross_margin, dtype: float64
Phân khúc Standard có tỷ suất lợi nhuận cao nhất với 0.31344174843884803

Q4. Trong web_traffic.csv, nguồn truy cập (traffic_source) nào có tỷ lệ thoát trung
bình (bounce_rate) thấp nhất trên tất cả các ngày xuất hiện nguồn đó trong cột traffic_source?
A) organic_search
B) paid_search
C) email_campaign
D) social_media

In [43]:
df_web.head()

,date,sessions,unique_visitors,page_views,bounce_rate,avg_session_duration_sec,traffic_source
0,2013-01-01,9760,7253,39093,0.00514,102.9,organic_search
1,2013-01-02,10456,8151,47611,0.00406,120.5,organic_search
2,2013-01-03,10076,7458,36963,0.00401,263.6,direct
3,2013-01-04,9973,8063,53078,0.00562,151.8,direct
4,2013-01-05,10223,7882,36790,0.00525,168.6,referral

In [44]:
df_web['date'] = pd.to_datetime(df_web['date'])

In [45]:
df_web.info()
print(df_web.isnull().sum())
print(df_web.duplicated().sum())
print(df_web.nunique().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      3652 non-null   datetime64[ns]
 1   sessions                  3652 non-null   int64
 2   unique_visitors           3652 non-null   int64
 3   page_views                3652 non-null   int64
 4   bounce_rate               3652 non-null   float64
 5   avg_session_duration_sec  3652 non-null   float64
 6   traffic_source            3652 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 199.8+ KB
date                        0
sessions                    0
unique_visitors             0
page_views                  0
bounce_rate                 0
avg_session_duration_sec    0
traffic_source              0
dtype: int64
0
16139

In [46]:
bounce_rate= df_web.groupby('traffic_source')['bounce_rate'].mean().sort_values()
print("Tỷ lệ bounce_rate trung bình theo từng web_traffic:",bounce_rate)
#tỷ lệ thấp nhất
min_source = bounce_rate.idxmin()
min_value = bounce_rate.min()
print(f"Nguồn '{min_source}' có tỷ lệ thoát trung bình thấp nhất ({min_value:.6f})")

Tỷ lệ bounce_rate trung bình theo từng web_traffic: traffic_source
email_campaign    0.004458
social_media      0.004476
paid_search       0.004478
referral          0.004499
organic_search    0.004504
direct            0.004511
Name: bounce_rate, dtype: float64
Nguồn 'email_campaign' có tỷ lệ thoát trung bình thấp nhất (0.004458)

In [32]:
df_promo.head()

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,NaN,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,NaN,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,NaN,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,NaN,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

In [34]:
df_promo.info()
print(df_promo.isnull().sum())
print(df_promo.duplicated().sum())
print(df_promo.nunique().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   promo_id             50 non-null     object
 1   promo_name           50 non-null     object
 2   promo_type           50 non-null     object
 3   discount_value       50 non-null     float64
 4   start_date           50 non-null     object
 5   end_date             50 non-null     object
 6   applicable_category  10 non-null     object
 7   promo_channel        50 non-null     object
 8   stackable_flag       50 non-null     int64
 9   min_order_value      50 non-null     int64
dtypes: float64(1), int64(2), object(7)
memory usage: 4.0+ KB
promo_id                0
promo_name              0
promo_type              0
discount_value          0
start_date              0
end_date                0
applicable_category    40
promo_channel           0
stackable_flag          0
min_order_value         0
dtype: int64
0
222

Q5. Tỷ lệ phần trăm các dòng trong order_items.csv có áp dụng khuyến mãi (tức là promo_id
không null) xấp xỉ là bao nhiêu?
A) 12%
B) 25%
C) 39%
D) 54%

In [39]:
tong = len(df_items)
print(f"Tổng số dòng: {tong:,}")
#lọc promo_id không bị
promo_applied = df_items['promo_id'].notna().sum()
per = (promo_applied/ tong) * 100
print(f"==> Tỷ lệ % các sản phẩm có áp dụng khuyến mãi là: {per:.2f}%")

Tổng số dòng: 714,669
==> Tỷ lệ % các sản phẩm có áp dụng khuyến mãi là: 38.66%

In [15]:
df_items.head()

,order_id,product_id,quantity,unit_price,discount_amount,promo_id,promo_id_2
0,1,2400,7,1138.22,0.0,NaN,NaN
1,2,609,7,10166.25,0.0,NaN,NaN
2,3,396,3,11220.33,0.0,NaN,NaN
3,4,635,5,10639.25,0.0,NaN,NaN
4,6,1935,1,1597.84,0.0,NaN,NaN

In [14]:
df_items.info()
print(df_items.isnull().sum())
print(df_items.duplicated().sum())
print(df_items.nunique().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 714669 entries, 0 to 714668
Data columns (total 7 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         714669 non-null  int64
 1   product_id       714669 non-null  int64
 2   quantity         714669 non-null  int64
 3   unit_price       714669 non-null  float64
 4   discount_amount  714669 non-null  float64
 5   promo_id         276316 non-null  object
 6   promo_id_2       206 non-null     object
dtypes: float64(2), int64(3), object(2)
memory usage: 38.2+ MB
order_id                0
product_id              0
quantity                0
unit_price              0
discount_amount         0
promo_id           438353
promo_id_2         714463
dtype: int64
0
1354382

In [5]:
df_or.head()

,order_id,order_date,customer_id,zip,order_status,payment_method,device_type,order_source
0,1,2012-07-04,58578,1109,delivered,credit_card,desktop,paid_search
1,2,2012-07-04,58621,1330,returned,cod,mobile,paid_search
2,3,2012-07-04,58811,1473,delivered,credit_card,desktop,direct
3,4,2012-07-04,59453,2360,delivered,credit_card,desktop,referral
4,6,2012-07-06,57821,2886,delivered,paypal,mobile,email_campaign

In [29]:
df_or.info()
print(df_or.isnull().sum())
print(df_or.duplicated().sum())
print(df_or.nunique().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 646945 entries, 0 to 646944
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        646945 non-null  int64
 1   order_date      646945 non-null  datetime64[ns]
 2   customer_id     646945 non-null  int64
 3   zip             646945 non-null  int64
 4   order_status    646945 non-null  object
 5   payment_method  646945 non-null  object
 6   device_type     646945 non-null  object
 7   order_source    646945 non-null  object
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 39.5+ MB
order_id          0
order_date        0
customer_id       0
zip               0
order_status      0
payment_method    0
device_type       0
order_source      0
dtype: int64
0
770976

In [7]:
df_or['order_date'] = pd.to_datetime(df_or['order_date'])

In [6]:
df_geo.head()

     zip       city region      district
0  15201  Hai Phong   East  District #13
1  15202     Phu Ly   East  District #13
2  15203   Viet Tri   East  District #13
3  15204  Bac Giang   East  District #13
4  15205  Bac Giang   East  District #13

Q7. Vùng (region) nào trong geography.csv tạo ra tổng doanh thu cao nhất trong sales_train.csv?
A) West
B) Central
C) East
D) Cả ba vùng có doanh thu xấp xỉ bằng nhau

In [22]:
#công thức revenue=(quantity*price)-discount
df_items['revenue']=(df_items['quantity']*df_items['unit_price'])-df_items['discount_amount']
print(df_items['revenue'])

0          7967.54
1         71163.75
2         33660.99
3         53196.25
4          1597.84
            ...
714664    35791.36
714665    36755.53
714666    59112.48
714667    23836.65
714668     4716.75
Name: revenue, Length: 714669, dtype: float64

In [28]:
#items gộp với order qua order_id, gộp với geo qua zip
df_merge = pd.merge(df_items, df_or, on='order_id', how='inner')
df_merge = pd.merge(df_merge, df_geo, on='zip', how='inner')
#revenue theo từng region
revenue_by_region = df_merge.groupby('region')['revenue'].sum().sort_values(ascending=False)
print('Tổng doanh thu của từng vùng:',revenue_by_region)
max_region = revenue_by_region.index[0]
max_revenue = revenue_by_region.iloc[0]
print(f'Vùng {max_region} tạo ra doanh thu cao nhất với tổng cộng {max_revenue:,.2f}')

Tổng doanh thu của từng vùng: region
East       7.291151e+09
Central    4.719491e+09
West       3.670227e+09
Name: revenue, dtype: float64
Vùng East tạo ra doanh thu cao nhất với tổng cộng 7,291,150,819.12